### PR TITLE
feat: c++ bindings

### PR DESCRIPTION
**Pull request by baszalmstra**
Builds on #40 

This PR adds preliminary C++ bindings. There is still stuff missing with regards to documentation and a proper CMake install but the functionality is there. A test that shows how to use the bindings can be found here: https://github.com/baszalmstra/resolvo/blob/feat/cpp_bindings/cpp/tests/solve.cpp#L165

My C++ is quite rusty (pun intended) so feedback is definitely welcome!

I added a `pixi.toml` to quickly get started with the code. Simply run:

```
pixi run test-cpp
```

to build and run the C++ tests.

### CODE REVIEW

**Review by wolfv — APPROVED** [review]

**Comment by jerily** [comment]
I have ported most of resolvo to C++ and I can share if you think there is any value to it. I am currently struggling with DisplayUnsat though. Just a heads up.

**Comment by wolfv** [comment]
Definitely, that would be amazing to see! I also know that the mamba-folks are looking into this! cc @JohanMabille @jjerphan

**Comment by jerily** [comment]
Please check your email. I have sent what I have so far. I was planning to contact you when it would have been fully completed.

**Comment by SylvainCorlay** [comment]
> I have ported most of resolvo to C++ and I can share if you think there is any value to it. I am currently struggling with DisplayUnsat though. Just a heads up.

Amazing.

**Comment by baszalmstra** [comment]
@jerily That's amazing! Great work! 

But I have to wonder, wouldn't you be able to use the bindings we just merged? I would very much like to consolidate efforts instead of fragmenting. I feel like it would be more beneficial for the larger community to all focus our efforts on a single code base than to have multiple implementations. That is exactly why I created these bindings in the first place. 

If you are missing things from our bindings, or if they are not accessible enough, I would be more than happy to figure out how we can make it better for your use case too! :)

**Comment by jerily** [comment]
Thanks a lot!

I started this port because there was nothing like it a few months back. I will have to check out the C++ bindings and if they suit my needs, yes, I will use them. I must say though that everything I build these days (in open source I mean) it's C/C++ so not sure where rust fits into that picture.

That said, I'm not looking to compete with resolvo. I'm glad it exists and I hope it prospers further. I just want to build the tool I am working on in way that makes sense to me.

I just shared the code in case someone finds it valuable. That's all :)

**Comment by baszalmstra** [comment]
@jerily Makes sense! 

You should be able to use our bindings using something akin to (from the top of my head):

```cmake
include(FetchContent)
FetchContent_Declare(
  Resolvo
  GIT_REPOSITORY https://github.com/mamba-org/resolvo.git
  GIT_TAG resolvo_cpp-v0.1.0)
FetchContent_MakeAvailable(Resolvo)
```

You should then have a `Resolvo` target that you can link to. This should have all the include- and library paths set up correctly.

The only downside of this approach is that you need to have [Rust installed on your system](https://www.rust-lang.org/tools/install).

I am also creating a conda package that has prebuilt binaries and doesn't require any Rust. (Not sure how familiar you are using that). Should be online in a few hours!

If you try this out, please share your thoughts! I would be very happy to facilitate making the bindings easier to use.

**Comment by jerily** [comment]
Thanks! I will check it out this week. At work at the moment - Java & Python :)

**Comment by jerily** [comment]
I have tried out the C++ bindings. Here are few notes:

- They work!!!
- It would have been nice if there were a few examples how to use all the features. I ended up using cpp/tests/solve.cpp
- I don't see any way to get the nice graph that explains why a problem is unsolvable, e.g.:
```
The following packages are incompatible
└─ asdf * can be installed with any of the following options:
   └─ asdf 1 would require
      └─ c >=2, <3, which can be installed with any of the following options:
         └─ c 2
└─ c 1 is locked, but another version is required as reported above
```

**Comment by jerily** [comment]
Figured out where the nice graph is. I am good!

**Comment by baszalmstra** [comment]
@jerily great! If you have suggestions for the API or if you have examples you can share Id love to hear it!

**Comment by jerily** [comment]
Just getting started. A quick one though is the for loop in display_merged_solvables. It needs to be:
```
        bool first = true;
        for (const auto& solvable : solvables) {
            if (!first) {
                ss << " | ";
            }

            ss << candidates[solvable.id].version;
            first = false;
        }
```

**Comment by baszalmstra** [comment]
Would you be able to open a PR?

**Comment by jerily** [comment]
Just got back from theater. I'm on it now.

**Comment by jjerphan** [comment]
Hi @jerily, would you be interested in publishing your C++ port of resolvo on GitHub? :)

**Comment by jerily** [comment]
Hi @jjerphan , yes, sure. Please note that DisplayUnsat is not finished and I turned to using C++ bindings myself. I can either place it on github now as it stands or finish it and then publish it by end of July. Please let me know what works for you best.

**Comment by jjerphan** [comment]
I would encourage you to publish it on GitHub, we might have been able to contribute to it to help you if we have time. :slightly_smiling_face:

**Comment by jerily** [comment]
Here it is: https://github.com/jerily/resolvo-cpp

I should be able to resume work on it after July 20.

**Comment by jerily** [comment]
Renamed the project to avoid clash with resolvo to satdepsolver-cpp: https://github.com/jerily/satdepsolver-cpp

Please let me know if that's ok.

**Pull request merged**
